### PR TITLE
Updated dependencies. Synfig 1.4 (beta)

### PR DESCRIPTION
**Pull request by ice0**

### CODE REVIEW

**Comment by ice0** [comment]
@bot build

**Comment by ice0** [comment]
bot, build

**Comment by eszlari** [comment]
@ice0 Note that Flathub allows you to publish beta builds, just create a branch called "beta", see:

https://blogs.gnome.org/alexl/2019/02/19/changes-in-flathub-land/

**Comment by ice0** [comment]
@eszlari Thank for pointing this out. I will check it!

**Pull request closed without merging**
