### PR TITLE
Update runtime to Gnome 44

### PR DESCRIPTION
**Pull request by SaadiSave**

### CODE REVIEW

**Comment by ice0** [comment]
We have an issue on Windows build (https://github.com/synfig/synfig/issues/2390)

Unfortunately after bumping to Gnome 41 this issue is now reproducible with flatpak. 
I will merge this PR after the issue is fixed. 

Thank you!

**Comment by SaadiSave** [comment]
> We have an issue on Windows build ([synfig/synfig#2390](https://github.com/synfig/synfig/issues/2390))
> 
> Unfortunately after bumping to Gnome 41 this issue is now reproducible with flatpak. I will merge this PR after the issue is fixed.
> 
> Thank you!

This is not reproducible on my machine (Ubuntu 20.04 LTS, flatpak version 1.6.5)

This is the output of `flatpak info`:
```
Synfig Studio - Create and edit 2D animations and compositions

          ID: org.synfig.SynfigStudio
         Ref: app/org.synfig.SynfigStudio/x86_64/test
        Arch: x86_64
      Branch: test
     Version: 1.4.2
     License: GPL-3.0
      Origin: synfigstudio-origin
  Collection: org.flathub.Stable.Build71140
Installation: user
   Installed: 78,8 MB
     Runtime: org.gnome.Platform/x86_64/41
         Sdk: org.gnome.Sdk/x86_64/41

      Commit: 8088d874e9bf907473411e7e8ccacd8b741fbe24674856a795cd03caa92348ab
     Subject: Update runtime to Gnome 41 (6fe114b3)
        Date: 2022-01-04 06:51:23 +0000
```

**Comment by SaadiSave** [comment]
bot, build

**Comment by ice0** [comment]
> This is not reproducible on my machine (Ubuntu 20.04 LTS, flatpak version 1.6.5)

Can you make a short video showing the process? I think maybe you missed some step while reproducing the problem?

**Comment by SaadiSave** [comment]
> > This is not reproducible on my machine (Ubuntu 20.04 LTS, flatpak version 1.6.5)
> 
> Can you make a short video showing the process? I think maybe you missed some step while reproducing the problem?

Apparently, I did miss a step. I can confirm that it crashes. I also noticed that the version here is 1.4.2, while the upstream version is 1.5.1. Is there something holding back the upgrade?

**Comment by ice0** [comment]
> Apparently, I did miss a step. I can confirm that it crashes. I also noticed that the version here is 1.4.2, while the upstream version is 1.5.1. Is there something holding back the upgrade?

Synfig has two versions: 1.4.x (stable) and 1.5.x (unstable/testing).

So 1.5.1 is located in beta branch: https://github.com/flathub/org.synfig.SynfigStudio/tree/beta

**Comment by bbhtt** [comment]
What's the status here? 41 is EOL now, you want 44.

**Comment by ice0** [comment]
> What's the status here? 41 is EOL now, you want 44.

Hi! The original issue has been fixed, so I need to test it again.
Can you bump it to 44?

**Comment by ice0** [comment]
Fixed in this commit: https://github.com/flathub/org.synfig.SynfigStudio/commit/b33c51820023ad4ddc812742552ddd1d2ff718d2

**Pull request closed without merging**
